### ISSUE TITLE
LIMES - Configuartion file

### ISSUE THREAD

**Issue by HFarah** [dice-group/LIMES-legacy#26]
Hello; I need your help please.
I have a problem with using LIMES when I have to use aggregate functions and compare more than one property. I am attaching here an excerpt from my configuration file. : 
`<METRIC>
ADD(0.5*levenshtein(x.prop:property2, y.prop:property2), 0.5*levenshtein(x.prop:property3, y.prop:property3))
</METRIC>`

In principle I must have a similarity link with this configuartion, instead I have an error message!
 INFO [main] (PPJoinController.java:155) - Getting links ...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at de.uni_leipzig.simba.controller.Parser.getTerms(Parser.java:144)
        at de.uni_leipzig.simba.controller.Parser.<init>(Parser.java:26)
        at de.uni_leipzig.simba.mapper.SimpleSetConstraintsMapper.getLinks(SimpleSetConstraintsMapper.java:67)
        at de.uni_leipzig.simba.controller.PPJoinController.run(PPJoinController.java:157)
        at de.uni_leipzig.simba.controller.PPJoinController.main(PPJoinController.java:32)

Thank you.

**Comment by Kleanthi** [comment]
Hello and sorry for the delayed answer.
Please use the new LIMES available at: https://github.com/dice-group/LIMES
We also have included a new user manual that will answer your question. 

The problem is that you are missing the thresholds of the atomic LS.
<METRIC> ADD(0.5*levenshtein(x.prop:property2, y.prop:property2)|threshold1, 0.5*levenshtein(x.prop:property3, y.prop:property3)|threshold2) </METRIC>
will do the trick.
